include:
  - proxy.yaml

services:
  web:
    image: cr.yandex/${REGISTRY_ID}/webapp:latest
    networks:
      backend:
        ipv4_address: 172.20.0.5
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - /opt/app/.env
